# Configuration for Graph Learning

# Model setup
checkpoints: 'model_checkpoints/'

# Training parameters
batch_size: 5
epochs: 50
learning_rate: 0.03
max_epochs: 50

# Data parameters
split: 'train'
root: 'data/Modelnet_resampled/'
