# Configuration for Graph Learning

# Model setup
checkpoints: 'model_checkpoints/'

# Training parameters
batch_size: 1
epochs: 10
learning_rate: 0.001

# Data parameters
split: 'train'
root: 'data/Modelnet/'
