# Configuration for Graph Learning

# Model setup
checkpoints: 'model_checkpoints/'

# Training parameters
batch_size: 1
epochs: 50
learning_rate: 0.003
max_epochs: 5

# Data parameters
split: 'train'
root: 'data/Modelnet_resampled/'
