# Configuration for Graph Learning

# Model setup
checkpoints: 'model_checkpoints/'

# Training parameters
batch_size: 2
epochs: 200
learning_rate: 0.05
max_epochs: 200

# Data parameters
split: 'train'
root: 'data/Modelnet_resampled/'
