# Configuration for Graph Learning

project_name: 'PointTransformer_Segmentation_SN'

# Device
device: 'cuda'

# Model setup
checkpoints: 'model_checkpoints/'
model: 'super'
subsampling: 'fps' # or grid 

# Training parameters
batch_size: 10
epochs: 200
learning_rate: 0.05
max_epochs: 200

# Data parameters
root: '../data/ShapeNet_Part/'
sample_size : 0.3  # only Stanford3d

# Model parameters
num_classes : 50
grid_size : [0.06,0.08,0.12,0.24]
k_up : 16
k_down : 16

# scheduler not implemented yet
step_size: 20

