# Configuration for Graph Learning

project_name: 'PointTransformer_Segmentation_SN'
run_name: 'SN_part_double_batch_size=30'

# Device
device: 'cuda'

# Model setup
checkpoints: 'model_checkpoints/'
model: 'double'
subsampling: 'fps' # fps or grid 

# Training parameters
batch_size: 30
epochs: 100
learning_rate: 0.05
max_epochs: 200

# Data parameters
root: 'data/ShapeNet_Part/'
sample_size : 0.3  # only Stanford3d

# Model parameters
num_classes : 50
grid_size : [0.03,0.06,0.10,0.20]
k_up : 16
k_down : 16

# scheduler not implemented yet
step_size: 20

