# Configuration for Graph Learning

project_name: 'PointTransformer_S3DIS'
run_name: 's3dis_base'
debug: False
data: 'S3DIS'

# Device
device: 'cuda'

# Model setup
checkpoints: 'model_checkpoints/'
model: 'standard'

# Training parameters
batch_size: 8
learning_rate: 0.5
max_epochs: 850
N_max : 60000
momentum: 0.9
weight_decay: 0.0001
milestones: [450,600]
class_weights: [1,1,1,1,1,1.5,1,1,1,1,1,1,1,1]

# Scheduler parameters
step_size: 300
step_gamma: 0.2

# Val parameters
batch_size_val: 2
N_max_val: null

# Testing?
test: True

# Data parameters
root: 'data/Stanford3dDataset/'
# only S3DIS
sample_size : 0.03

# Model parameters
num_classes : 14
num_categories: None #only ShapeNetPart
k_up : 3
k_down : 16
blocks: [1,2,3,3,1]
value_down: [1,0.06,0.15,0.375,0.9375]
channels: [32, 64, 128, 256, 512]
strides: [1,2,4,4,4]
in_channels: 6
subsampling: 'grid' # fps or grid